function Es_ = w_objs_s(geome_,parame_,finite_,gerjoii_,ks)
% ..............................................................................
% computes objective function value for a perturbation of the parameters
% in the direction of the gradient with a step-size ks.
% ..............................................................................
% clean dc first
if isfield(gerjoii_,'dc')
  gerjoii_=rmfield(gerjoii_,'dc');
end
if isfield(parame_,'dc')
  parame_=rmfield(parame_,'dc');
end
if isfield(finite_,'dc')
  finite_=rmfield(finite_,'dc');
end
% ..............................................................................
% load source, receivers, measuring operator, observed data & std
% ..............................................................................
% [parame_,gerjoii_] = w_load(parame_,gerjoii_,is);
Nw = sparse_diag(parame_.natu.w.N);
% ..............................................................................
% perturb
% ..............................................................................
parame_.w.sigma = parame_.w.sigma .* ...
                    exp( -ks*parame_.w.sigma .* gerjoii_.w.g_s);
% ..............................................................................
% fwd model
% ..............................................................................
[~,gerjoii_] = w_fwd_(geome_,parame_,finite_,gerjoii_,0);
% ..............................................................................
% filter wavefields
% ..............................................................................
% if strcmp(gerjoii_.w.regu.f_yesno,'YES')
parame_.natu.w.d_2d = filt_gauss(parame_.natu.w.d_2d,geome_.w.dt,...
                               gerjoii_.w.regu.f_,gerjoii_.w.regu.f__,8);%[Hz]
gerjoii_.w.d_2d = filt_gauss(gerjoii_.w.d_2d,geome_.w.dt,...
                               gerjoii_.w.regu.f_,gerjoii_.w.regu.f__,8);%[Hz]
% end
% ..............................................................................
% obj
% ..............................................................................
Es_ = w_E(parame_.natu.w.d_2d,gerjoii_.w.d_2d,Nw,gerjoii_.w.obj_FNC);
Es_ = Es_ / ( parame_.natu.w.d_2d(:).' * parame_.natu.w.d_2d(:) );
end